services:
  db:
    image: mysql:latest
    container_name: mysql-db
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    restart: always
    depends_on:
      - backend

volumes:
  db_data:
    driver: local
